### ISSUE TITLE
Runtime exit handler error

### ISSUE THREAD

**Issue by Binyang2014** [microsoft/openpai-runtime#18]
Sometimes runtime exit handler will report:
Error:2020/07/31 07:49:23 logger.go:49: failed to get truncate exit info, err: failed to truncate the exit info
Error:2020/07/31 07:49:23 logger.go:49: runtime failed to handle exit info fatal: dumping summary info: failed to truncate the exit info

Need to investigate why this happens

**Comment by fanyangCS** [comment]
@Binyang2014 , could you explain the root cause here?

**Comment by Binyang2014** [comment]
The root cause is:
When truncate log, we calculate the number of characters to be truncated based on `current_exit_info_size_in_yaml_format - expect_exit_info_size` . Then we truncate the log in each filed.
We don't recalculate the `exit_info_size_in_yaml_format` after truncate each field. But there is a gap between `yaml-formatted-size` and `non-yaml-formatted-size` .
Suppose we can truncate `n`  characters  in field `A`. After format the exitInfo into yaml, the reduced size will be large than `n`, especially when log file content is large.

So we recalculate the exitInfo size after truncate each filed. If we still failed to truncate the log, we will return a minimal exitInfo, which only contain `exitCode` , `originalUserCode` and `matchedGpuInfo`.
