### ISSUE TITLE
How can I use my own runtime?

### ISSUE THREAD

**Issue by zerozakiihitoshiki** [microsoft/openpai-runtime#33]
I have rebuilt my runtime image and pushed it to my repository in Dockerhub, but I don't know how to change rest-server config to use it. Can anyone help?

**Comment by Binyang2014** [comment]
https://github.com/microsoft/pai/blob/bf41920d6d7319e310760df5b9ad1bb4a1531241/src/rest-server/deploy/rest-server.yaml.template#L62
Please change this line to your image name.
